# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vitarana_drone/edrone_cmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class edrone_cmd(genpy.Message):
  _md5sum = "dc07470079f832efd9aebe0e4687ea6f"
  _type = "vitarana_drone/edrone_cmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 rcRoll
float64 rcPitch
float64 rcYaw
float64 rcThrottle
float64 aux1
float64 aux2
float64 aux3
float64 aux4
"""
  __slots__ = ['rcRoll','rcPitch','rcYaw','rcThrottle','aux1','aux2','aux3','aux4']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rcRoll,rcPitch,rcYaw,rcThrottle,aux1,aux2,aux3,aux4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(edrone_cmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.rcRoll is None:
        self.rcRoll = 0.
      if self.rcPitch is None:
        self.rcPitch = 0.
      if self.rcYaw is None:
        self.rcYaw = 0.
      if self.rcThrottle is None:
        self.rcThrottle = 0.
      if self.aux1 is None:
        self.aux1 = 0.
      if self.aux2 is None:
        self.aux2 = 0.
      if self.aux3 is None:
        self.aux3 = 0.
      if self.aux4 is None:
        self.aux4 = 0.
    else:
      self.rcRoll = 0.
      self.rcPitch = 0.
      self.rcYaw = 0.
      self.rcThrottle = 0.
      self.aux1 = 0.
      self.aux2 = 0.
      self.aux3 = 0.
      self.aux4 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.rcRoll, _x.rcPitch, _x.rcYaw, _x.rcThrottle, _x.aux1, _x.aux2, _x.aux3, _x.aux4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.rcRoll, _x.rcPitch, _x.rcYaw, _x.rcThrottle, _x.aux1, _x.aux2, _x.aux3, _x.aux4,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.rcRoll, _x.rcPitch, _x.rcYaw, _x.rcThrottle, _x.aux1, _x.aux2, _x.aux3, _x.aux4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.rcRoll, _x.rcPitch, _x.rcYaw, _x.rcThrottle, _x.aux1, _x.aux2, _x.aux3, _x.aux4,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
