// Generated by gencpp from file pkg_ros_basics/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PKG_ROS_BASICS_MESSAGE_ADDTWOINTS_H
#define PKG_ROS_BASICS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <pkg_ros_basics/AddTwoIntsRequest.h>
#include <pkg_ros_basics/AddTwoIntsResponse.h>


namespace pkg_ros_basics
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace pkg_ros_basics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_ros_basics::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::pkg_ros_basics::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::pkg_ros_basics::AddTwoInts > {
  static const char* value()
  {
    return "pkg_ros_basics/AddTwoInts";
  }

  static const char* value(const ::pkg_ros_basics::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_ros_basics::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::pkg_ros_basics::AddTwoInts >
template<>
struct MD5Sum< ::pkg_ros_basics::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_ros_basics::AddTwoInts >::value();
  }
  static const char* value(const ::pkg_ros_basics::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_ros_basics::AddTwoIntsRequest> should match
// service_traits::DataType< ::pkg_ros_basics::AddTwoInts >
template<>
struct DataType< ::pkg_ros_basics::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_ros_basics::AddTwoInts >::value();
  }
  static const char* value(const ::pkg_ros_basics::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_ros_basics::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::pkg_ros_basics::AddTwoInts >
template<>
struct MD5Sum< ::pkg_ros_basics::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_ros_basics::AddTwoInts >::value();
  }
  static const char* value(const ::pkg_ros_basics::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_ros_basics::AddTwoIntsResponse> should match
// service_traits::DataType< ::pkg_ros_basics::AddTwoInts >
template<>
struct DataType< ::pkg_ros_basics::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_ros_basics::AddTwoInts >::value();
  }
  static const char* value(const ::pkg_ros_basics::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_ROS_BASICS_MESSAGE_ADDTWOINTS_H
