// Generated by gencpp from file vitarana_drone/Gripper.msg
// DO NOT EDIT!


#ifndef VITARANA_DRONE_MESSAGE_GRIPPER_H
#define VITARANA_DRONE_MESSAGE_GRIPPER_H

#include <ros/service_traits.h>


#include <vitarana_drone/GripperRequest.h>
#include <vitarana_drone/GripperResponse.h>


namespace vitarana_drone
{

struct Gripper
{

typedef GripperRequest Request;
typedef GripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Gripper
} // namespace vitarana_drone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vitarana_drone::Gripper > {
  static const char* value()
  {
    return "b6ef517238124133d1f6964a49370da8";
  }

  static const char* value(const ::vitarana_drone::Gripper&) { return value(); }
};

template<>
struct DataType< ::vitarana_drone::Gripper > {
  static const char* value()
  {
    return "vitarana_drone/Gripper";
  }

  static const char* value(const ::vitarana_drone::Gripper&) { return value(); }
};


// service_traits::MD5Sum< ::vitarana_drone::GripperRequest> should match
// service_traits::MD5Sum< ::vitarana_drone::Gripper >
template<>
struct MD5Sum< ::vitarana_drone::GripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vitarana_drone::Gripper >::value();
  }
  static const char* value(const ::vitarana_drone::GripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vitarana_drone::GripperRequest> should match
// service_traits::DataType< ::vitarana_drone::Gripper >
template<>
struct DataType< ::vitarana_drone::GripperRequest>
{
  static const char* value()
  {
    return DataType< ::vitarana_drone::Gripper >::value();
  }
  static const char* value(const ::vitarana_drone::GripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vitarana_drone::GripperResponse> should match
// service_traits::MD5Sum< ::vitarana_drone::Gripper >
template<>
struct MD5Sum< ::vitarana_drone::GripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vitarana_drone::Gripper >::value();
  }
  static const char* value(const ::vitarana_drone::GripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vitarana_drone::GripperResponse> should match
// service_traits::DataType< ::vitarana_drone::Gripper >
template<>
struct DataType< ::vitarana_drone::GripperResponse>
{
  static const char* value()
  {
    return DataType< ::vitarana_drone::Gripper >::value();
  }
  static const char* value(const ::vitarana_drone::GripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VITARANA_DRONE_MESSAGE_GRIPPER_H
